"""empty message

Revision ID: 56107568874d
Revises: 909704fd50e2
Create Date: 2023-09-16 03:50:46.763912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56107568874d'
down_revision = '909704fd50e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_phone_number', table_name='user')
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.create_index('ix_user_phone_number', 'user', ['phone_number'], unique=False)
    # ### end Alembic commands ###
