"""empty message

Revision ID: 7fda9da80f9b
Revises: 7e03d1ebe95d
Create Date: 2023-09-20 10:37:42.503575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fda9da80f9b'
down_revision = '7e03d1ebe95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
       


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image_url', sa.VARCHAR(length=256), nullable=True))
    op.create_index('ix_product_name', 'product', ['name'], unique=False)
    op.alter_column('product', 'price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
