"""empty message

Revision ID: 909704fd50e2
Revises: 
Create Date: 2023-09-16 03:49:33.518291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909704fd50e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
